# Generated by Django 3.1.1 on 2020-09-28 10:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='uname')),
                ('last_name', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='uname')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('uname', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='uname')),
                ('uid', models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='uid')),
                ('date_reg', models.DateTimeField(auto_now_add=True, verbose_name='date_reg')),
                ('shop_id', models.CharField(default='1000', max_length=250, primary_key=True, serialize=False, unique=True, verbose_name='shop_id')),
                ('cart_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='cart_number')),
                ('id_moaref', models.CharField(blank=True, max_length=250, null=True, verbose_name='id_moaref')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
