# Generated by Django 3.1.1 on 2020-09-28 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='comment')),
                ('uname', models.CharField(blank=True, max_length=250, null=True, verbose_name='uname')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('id_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blog')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
