# Generated by Django 3.1.1 on 2020-09-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(blank=True, max_length=250, null=True, verbose_name='uname')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
