# Generated by Django 3.1.1 on 2020-09-28 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('address', models.TextField(max_length=300, verbose_name='name')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
