# Generated by Django 3.1.1 on 2020-09-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=250, null=True, verbose_name='username')),
                ('value', models.CharField(blank=True, max_length=250, null=True, verbose_name='value')),
                ('test', models.IntegerField(blank=True, default=0, null=True, verbose_name='test')),
                ('pay_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='pay_id')),
            ],
        ),
    ]
