# Generated by Django 3.1.1 on 2020-09-28 10:48

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '__first__'),
        ('shop', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/dolls/', verbose_name='picture')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='price')),
                ('using_datetime', models.CharField(blank=True, max_length=250, null=True, verbose_name='using datetinme')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.TextField(blank=True, max_length=10000, null=True, verbose_name='address')),
                ('click', models.IntegerField(blank=True, default=0, null=True, verbose_name='click')),
                ('alt', models.CharField(blank=True, max_length=250, null=True, verbose_name='alt')),
                ('x', models.FloatField(blank=True, default=0.0, null=True, verbose_name='x')),
                ('y', models.FloatField(blank=True, default=0.0, null=True, verbose_name='y')),
                ('meta_word', models.CharField(blank=True, max_length=250, null=True, verbose_name='meta word')),
                ('meta_description', models.CharField(blank=True, max_length=250, null=True, verbose_name='meta description')),
                ('doll_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='doll count')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.fgroup')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
        ),
    ]
