# Generated by Django 3.1.1 on 2020-09-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='g_id')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/posts/', verbose_name='picture')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='count')),
            ],
        ),
    ]
