# Generated by Django 3.1.1 on 2020-09-28 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dolls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('customerid', models.CharField(blank=True, max_length=250, null=True, verbose_name='customer id')),
                ('payid', models.CharField(blank=True, max_length=250, null=True, verbose_name='pay id')),
                ('pay_amount', models.IntegerField(blank=True, null=True, verbose_name='pay amount')),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dolls.doll')),
            ],
        ),
    ]
